################################################################################
#       Setting dont_touch and dont_use preserve setting
################################################################################
catch {set_db base_cell:DFFYQ_X1M_A9TR .dont_use true}
catch {set_db base_cell:DFFYQ_X2M_A9TR .dont_use true}
catch {set_db base_cell:DFFYQ_X3M_A9TR .dont_use true}
catch {set_db base_cell:DFFYQ_X4M_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X0P5B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X0P6B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X0P7B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X0P8B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X11B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X13B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X16B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X1B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X1P2B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X1P4B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X1P7B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X2B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X2P5B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X3B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X3P5B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X4B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X5B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X6B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X7P5B_A9TR .dont_use true}
catch {set_db base_cell:FRICG_X9B_A9TR .dont_use true}
catch {set_db base_cell:RF1R1WS_X1M_A9TR .dont_use true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TR .dont_use true}
catch {set_db base_cell:RF1R1WS_X2M_A9TR .dont_use true}
catch {set_db base_cell:RF1R2WS_X1M_A9TR .dont_use true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TR .dont_use true}
catch {set_db base_cell:RF1R2WS_X2M_A9TR .dont_use true}
catch {set_db base_cell:RF2R1WS_X1M_A9TR .dont_use true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TR .dont_use true}
catch {set_db base_cell:RF2R1WS_X2M_A9TR .dont_use true}
catch {set_db base_cell:RF2R2WS_X1M_A9TR .dont_use true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TR .dont_use true}
catch {set_db base_cell:RF2R2WS_X2M_A9TR .dont_use true}
catch {set_db base_cell:SDFFYQ_X1M_A9TR .dont_use true}
catch {set_db base_cell:SDFFYQ_X2M_A9TR .dont_use true}
catch {set_db base_cell:SDFFYQ_X3M_A9TR .dont_use true}
catch {set_db base_cell:SDFFYQ_X4M_A9TR .dont_use true}
catch {set_db base_cell:DFFYQ_X1M_A9TL .dont_use true}
catch {set_db base_cell:DFFYQ_X2M_A9TL .dont_use true}
catch {set_db base_cell:DFFYQ_X3M_A9TL .dont_use true}
catch {set_db base_cell:DFFYQ_X4M_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X0P5B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X0P6B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X0P7B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X0P8B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X11B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X13B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X16B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X1B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X1P2B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X1P4B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X1P7B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X2B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X2P5B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X3B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X3P5B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X4B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X5B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X6B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X7P5B_A9TL .dont_use true}
catch {set_db base_cell:FRICG_X9B_A9TL .dont_use true}
catch {set_db base_cell:RF1R1WS_X1M_A9TL .dont_use true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TL .dont_use true}
catch {set_db base_cell:RF1R1WS_X2M_A9TL .dont_use true}
catch {set_db base_cell:RF1R2WS_X1M_A9TL .dont_use true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TL .dont_use true}
catch {set_db base_cell:RF1R2WS_X2M_A9TL .dont_use true}
catch {set_db base_cell:RF2R1WS_X1M_A9TL .dont_use true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TL .dont_use true}
catch {set_db base_cell:RF2R1WS_X2M_A9TL .dont_use true}
catch {set_db base_cell:RF2R2WS_X1M_A9TL .dont_use true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TL .dont_use true}
catch {set_db base_cell:RF2R2WS_X2M_A9TL .dont_use true}
catch {set_db base_cell:SDFFYQ_X1M_A9TL .dont_use true}
catch {set_db base_cell:SDFFYQ_X2M_A9TL .dont_use true}
catch {set_db base_cell:SDFFYQ_X3M_A9TL .dont_use true}
catch {set_db base_cell:SDFFYQ_X4M_A9TL .dont_use true}
catch {set_db base_cell:DFFYQ_X1M_A9TH .dont_use true}
catch {set_db base_cell:DFFYQ_X2M_A9TH .dont_use true}
catch {set_db base_cell:DFFYQ_X3M_A9TH .dont_use true}
catch {set_db base_cell:DFFYQ_X4M_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X0P5B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X0P6B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X0P7B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X0P8B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X11B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X13B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X16B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X1B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X1P2B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X1P4B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X1P7B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X2B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X2P5B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X3B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X3P5B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X4B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X5B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X6B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X7P5B_A9TH .dont_use true}
catch {set_db base_cell:FRICG_X9B_A9TH .dont_use true}
catch {set_db base_cell:RF1R1WS_X1M_A9TH .dont_use true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TH .dont_use true}
catch {set_db base_cell:RF1R1WS_X2M_A9TH .dont_use true}
catch {set_db base_cell:RF1R2WS_X1M_A9TH .dont_use true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TH .dont_use true}
catch {set_db base_cell:RF1R2WS_X2M_A9TH .dont_use true}
catch {set_db base_cell:RF2R1WS_X1M_A9TH .dont_use true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TH .dont_use true}
catch {set_db base_cell:RF2R1WS_X2M_A9TH .dont_use true}
catch {set_db base_cell:RF2R2WS_X1M_A9TH .dont_use true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TH .dont_use true}
catch {set_db base_cell:RF2R2WS_X2M_A9TH .dont_use true}
catch {set_db base_cell:SDFFYQ_X1M_A9TH .dont_use true}
catch {set_db base_cell:SDFFYQ_X2M_A9TH .dont_use true}
catch {set_db base_cell:SDFFYQ_X3M_A9TH .dont_use true}
catch {set_db base_cell:SDFFYQ_X4M_A9TH .dont_use true}
catch {set_db base_cell:DFFYQ_X1M_A9TR .dont_touch true}
catch {set_db base_cell:DFFYQ_X2M_A9TR .dont_touch true}
catch {set_db base_cell:DFFYQ_X3M_A9TR .dont_touch true}
catch {set_db base_cell:DFFYQ_X4M_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X0P5B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X0P6B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X0P7B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X0P8B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X11B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X13B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X16B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X1B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X1P2B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X1P4B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X1P7B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X2B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X2P5B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X3B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X3P5B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X4B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X5B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X6B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X7P5B_A9TR .dont_touch true}
catch {set_db base_cell:FRICG_X9B_A9TR .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1M_A9TR .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TR .dont_touch true}
catch {set_db base_cell:RF1R1WS_X2M_A9TR .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1M_A9TR .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TR .dont_touch true}
catch {set_db base_cell:RF1R2WS_X2M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R1WS_X2M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TR .dont_touch true}
catch {set_db base_cell:RF2R2WS_X2M_A9TR .dont_touch true}
catch {set_db base_cell:SDFFYQ_X1M_A9TR .dont_touch true}
catch {set_db base_cell:SDFFYQ_X2M_A9TR .dont_touch true}
catch {set_db base_cell:SDFFYQ_X3M_A9TR .dont_touch true}
catch {set_db base_cell:SDFFYQ_X4M_A9TR .dont_touch true}
catch {set_db base_cell:DFFYQ_X1M_A9TL .dont_touch true}
catch {set_db base_cell:DFFYQ_X2M_A9TL .dont_touch true}
catch {set_db base_cell:DFFYQ_X3M_A9TL .dont_touch true}
catch {set_db base_cell:DFFYQ_X4M_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X0P5B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X0P6B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X0P7B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X0P8B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X11B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X13B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X16B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X1B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X1P2B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X1P4B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X1P7B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X2B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X2P5B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X3B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X3P5B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X4B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X5B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X6B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X7P5B_A9TL .dont_touch true}
catch {set_db base_cell:FRICG_X9B_A9TL .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1M_A9TL .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TL .dont_touch true}
catch {set_db base_cell:RF1R1WS_X2M_A9TL .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1M_A9TL .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TL .dont_touch true}
catch {set_db base_cell:RF1R2WS_X2M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R1WS_X2M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TL .dont_touch true}
catch {set_db base_cell:RF2R2WS_X2M_A9TL .dont_touch true}
catch {set_db base_cell:SDFFYQ_X1M_A9TL .dont_touch true}
catch {set_db base_cell:SDFFYQ_X2M_A9TL .dont_touch true}
catch {set_db base_cell:SDFFYQ_X3M_A9TL .dont_touch true}
catch {set_db base_cell:SDFFYQ_X4M_A9TL .dont_touch true}
catch {set_db base_cell:DFFYQ_X1M_A9TH .dont_touch true}
catch {set_db base_cell:DFFYQ_X2M_A9TH .dont_touch true}
catch {set_db base_cell:DFFYQ_X3M_A9TH .dont_touch true}
catch {set_db base_cell:DFFYQ_X4M_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X0P5B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X0P6B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X0P7B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X0P8B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X11B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X13B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X16B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X1B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X1P2B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X1P4B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X1P7B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X2B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X2P5B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X3B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X3P5B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X4B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X5B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X6B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X7P5B_A9TH .dont_touch true}
catch {set_db base_cell:FRICG_X9B_A9TH .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1M_A9TH .dont_touch true}
catch {set_db base_cell:RF1R1WS_X1P4M_A9TH .dont_touch true}
catch {set_db base_cell:RF1R1WS_X2M_A9TH .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1M_A9TH .dont_touch true}
catch {set_db base_cell:RF1R2WS_X1P4M_A9TH .dont_touch true}
catch {set_db base_cell:RF1R2WS_X2M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R1WS_X1P4M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R1WS_X2M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R2WS_X1P4M_A9TH .dont_touch true}
catch {set_db base_cell:RF2R2WS_X2M_A9TH .dont_touch true}
catch {set_db base_cell:SDFFYQ_X1M_A9TH .dont_touch true}
catch {set_db base_cell:SDFFYQ_X2M_A9TH .dont_touch true}
catch {set_db base_cell:SDFFYQ_X3M_A9TH .dont_touch true}
catch {set_db base_cell:SDFFYQ_X4M_A9TH .dont_touch true}
